### ISSUE TITLE
Market detail component

### ISSUE THREAD

**Issue by niran** [AugurProject/augur-client#13]
![img_20150426_003523](https://cloud.githubusercontent.com/assets/106437/7336029/61d1b6ec-ebac-11e4-97d7-1255f3d59ac6.jpg)

Sell buttons only show up if you own shares of that outcome. For elements that require Augur's web service (#6), we should just put in placeholders for now.

Buy/Sell take you to a trade screen with that keeps the same image/description header.

```
Purchase Shares

Yes

57%

_____ shares (X cash)

[ Buy ]

If the outcome of this question is Yes, your shares could
approach their maximum worth of Y cash.
```

Clicking "buy" pops up a confirmation modal.

```
Will Hillary Clinton win the 2016 U.S. Presidential Election?

Click confirm to purchase X shares of the **Yes** outcome for Y cash.

[ Cancel ] [ Confirm ]
```

Thoughts on this sketch?

**Comment by joeykrug** [comment]
Forecast history like this would be great

**Comment by joeykrug** [comment]
history not needed for alpha
