### ISSUE TITLE
Holdings component

### ISSUE THREAD

**Issue by niran** [AugurProject/augur-client#15]
From https://github.com/AugurProject/augur-client/wiki/Specification:

The holdings page displays a list of event outcomes with the number of outcome tokens held, their current price, and the current total value of the user's holdings of a given outcome. It also displays the total value of all held event outcomes. Each outcome links to its corresponding event detail page, where the user can buy and sell shares.

Users can send reputation to other accounts from the holdings page.

**Comment by scottzer0** [comment]
shifting this to be move of an account overview (asset balances/actions, recent transaction, upcoming votes, etc.) with options to dive deeper when appropriate (see all your transaction, etc.)

**Comment by niran** [comment]
I think upcoming votes should go in the ballots component. Most users are traders or observers, who don't have any reputation to vote with. They should be able to ignore the ballots component altogether and never come across voting information that is irrelevant or confusing to them.

The main goal of the holdings component should be to tell people about their funds that are tied up in Augur. Transactions per asset and overall would probably be better off as a page you can get to from the holdings screen. Each asset could have a "transaction history" link.
