### ISSUE TITLE
Feature request: auto-refresh and progress bar for addMarket

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-client#19]
Since adding a market takes ~24 seconds or so in all, I think it would be great if there was a progress bar (or some other visual indicator).  Maybe you could have a checklist appear somewhere (sidebar or something?) and visually check off:
- event submitted
- event accepted
- market submitted
- market accepted

But, maybe this would emphasize the difference between events/markets too much?  I dunno, just a progress bar that jumped to 25%, 50%, 75%, 100% on the 4 steps listed above would be pretty cool.

Also, suggest making the markets display auto-refresh once the market is accepted -- maybe put that in the onSuccess callback in EthereumClient.addMarket?

**Comment by scottzer0** [comment]
I have something more basic and elegant in mind for this dissonance.  The client wil adding the market/event to is store as pending and either unflag it as such when it lon longer is, or remove and message user if it fails for whatever reason.

**Comment by scottzer0** [comment]
this has been implemented as pending markets
