### ISSUE TITLE
Doing consensus

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#21]
So people will need to be able to call consensus (it has to be called multiple times to do a full round - it has many calls).  So basically call `def checkQuorum(branch)` from the checkQuorum contract, if that returns 1/true then consensus is ready to be called.

Anyone can call consensus.

Call `def dispatch(branchNumber)` multiple times until eventually it returns `9` which means that that round of consensus is complete.

**Comment by niran** [comment]
Calling `dispatch` costs ether, right? What makes a user want to call it?

**Comment by joeykrug** [comment]
Nothing in this version (besides the fact that you will never have consensus or payouts unless it is called) --- there are plans to add a nice incentive but I didn't want to overwhelm the UI with that concept atm --- am making a blog post about it actually that explains how the incentive mechanism works / should be implemented
