### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#23]
So for reporting... to get a list of events happening in the current report period call
`def makeBallot(branch, votePeriod)` in expiring events --- votePeriod is (block.number/periodLength) - 1  This is a list of all events you need to report on in order.

Now make a report --- basically an array of values.
So for no no yes no yes indeterminate your array should look like:
`[2**64, 2**64, 2*2**64, 2**64, 2*2**64, (3*2**64)/2]`

Get (block.number/periodLength) - 1 via a call, go to makeReports and call
`def checkReportValidity(branch, report:arr, votePeriod)` with that vote period.  Make sure to save the report *securely* client side.

Now call
`def hashReport(report: arr, salt)` using a random salt generated with some nice entropy.

You now have a report hash.

Submit this to the network with 
`def submitReportHash(branch, reportHash, votePeriod)` using a live sendTransaction

Note: for the first half of the voting period (so the first 4 weeks you can submit this hash (and update it if you like).

Now during the second half of the vote period (the last 4 weeks) you can submit your real report

Send a transaction to `def report(branch, report:arr, votePeriod, salt)` and you'll have submitted a report.

As soon as a period changes (e.g. block.number/periodLength increases by 1, it's time to vote on (block.number/periodLength) - 1 again).  Remember first half is hash, second is the plaintext report.

Now for something fun:
If someone tries to collude during the first half, and you can provide their salt and report and address to the network, you get their rep (because they are a cheater)!
Send a transaction to  `def slashRep(branch, votePeriod, salt, report:arr, reporter)` to do this.

**Comment by niran** [comment]
Here's the spec version of this: https://github.com/AugurProject/augur-client/wiki/Specification#ballots
