### ISSUE TITLE
DOM error when creating a market

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#32]
```Uncaught Error: Invariant Violation: Component (with keys: getDOMNode,_handleChange,props,context,state,refs,_reactInternalInstance) contains `render` method but is not mounted in the DOMinvariant @ augur.js:96509findDOMNode @ augur.js:95504ReactBrowserComponentMixin.getDOMNode @ augur.js:82198ReactClass.createClass.componentDidUpdate @ augur.js:86229assign.notifyAll @ augur.js:78723ON_DOM_READY_QUEUEING.close @ augur.js:91892Mixin.closeAll @ augur.js:94775Mixin.perform @ augur.js:94716Mixin.perform @ augur.js:94702assign.perform @ augur.js:92914flushBatchedUpdates @ augur.js:92994wrapper @ augur.js:91321Mixin.closeAll @ augur.js:94775Mixin.perform @ augur.js:94716ReactDefaultBatchingStrategy.batchedUpdates @ augur.js:87074batchedUpdates @ augur.js:92929ReactEventListener.dispatchEvent @ augur.js:88836```

**Comment by joeykrug** [comment]
Create market works fine btw, just this weird DOM error

**Comment by scottzer0** [comment]
there's will be react errors like this when data regression (geth abi issues, contracts missing).  closing this.
