### ISSUE TITLE
Share simulated call doesn't seem to be working

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#35]
price == 0 no matter what

![screen shot 2015-05-18 at 7 02 53 pm](https://cloud.githubusercontent.com/assets/5925937/7694139/d7fce0ee-fd90-11e4-939d-52deac13c8f7.png)

**Comment by scottzer0** [comment]
https://github.com/AugurProject/augur.js/issues/13

**Comment by joeykrug** [comment]
Jack fixed
