### ISSUE TITLE
Dispatch Calling Over & Over

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#36]
Dispatch is caught up and it just keeps spamming dispatch tx spending all my ether regardless of it already being caught up.

**Comment by tinybike** [comment]
That's where all my ether went!! >:(

**Comment by niran** [comment]
lol, please excuse our untested financial software. But on a serious note, automated tests for transaction sending are required before Frontier so people don't hate us.

**Comment by niran** [comment]
In fact, it might be worth keeping the contracts off of the live network and pointing everyone at a test net until things are solid.

**Comment by scottzer0** [comment]
a fix has been implemented
