### ISSUE TITLE
Buy/Sell Shares Simulated Buy/sell not working

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#53]
Uncaught TypeError: this.state.simulation.cost.toFixed is not a function

occurs upon an attempt to buy / sell shares

So getSimulatedBuy and getSimulatedSell were revamped: they return [cost, price] --- price being the new price for that outcome if you bought, and cost being how much money you will get paid if you sell, or how much money you will have to pay if you buy.

**Comment by tinybike** [comment]
Buy/sell shares (and the simulations) are working as of d550f4fd701b03cd808aece4177d6f186ce6d0fa.
