### ISSUE TITLE
Refresh odds when someone buys/sells shares dynamically instead of having to refresh

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#61]
Get this info from a filter on the buy/sell shares logs

**Comment by tinybike** [comment]
Added this in f36030fa5940e6765a690c71daadab625f8df965 to markets that you've traded in yourself; the onSuccess callback now updates the prices/probabilities.  I'll implement the full version of this (dynamic updating when anyone -- not just you -- buys/sells) post-alpha, when I have time to add proper filters to augur.js.
