### ISSUE TITLE
Make fetching of markets asynchronous so demo users don't have to wait 30-40 seconds to load ui

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#67]

**Comment by tinybike** [comment]
Asynchronous getMarkets has been in augur.js and clients/EthereumClient.js for 6 weeks or so:  https://github.com/AugurProject/augur-client/blob/develop/app/clients/EthereumClient.js#L305-L374.  Just needs to be hooked up to the appropriate flux data stores and/or DOM elements need to be made available so markets can be dumped into them as they load.  (This is a one-liner in jQuery, but no idea how to do this in React/Flux.)

**Comment by joeykrug** [comment]
It's probably a half liner in flux!

**Comment by tinybike** [comment]
Zing

**Comment by scottzer0** [comment]
closing this as it seems done in this spirit.  more will be done soon and a new issue will be made to track that.
