### ISSUE TITLE
When attempting to use either the local client or client.augur.net, get message "Failed to Connect to Ethereum"

### ISSUE THREAD

**Issue by gnomicperfect** [AugurProject/augur-client#81]
"Failed to connect to Ethereum

Augur requires a local node of the Ethereum client running

Visit the ethereum github wiki for help installing the latest client

If geth is installed:
geth --rpc --rpccorsdomain http://localhost:8080 --shh --unlock primary"

geth is actually running and functioning normally.
 Followed all instructions to install the augur alpha local client.

**Comment by tinybike** [comment]
Augur is on a private chain (separate from the public testnet) for now, until the Olympic punishment is over.  To use the private chain, you need to run geth with the following flags:
```
geth --rpc --rpccorsdomain "http://client.augur.net http://localhost:8080" --shh --maxpeers "64" --networkid 1010101 --datadir "~/.augur" --protocolversion "59" --bootnodes "enode://035b7845dfa0c0980112abdfdf4dc11087f56b77e10d2831f186ca12bc00f5b9327c427d03d9cd8106db01488905fb2200b5706f9e41c5d75885057691d9997c@[::]:30303" unlock primary
```
