### ISSUE TITLE
New market modal

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur-client#9]
The creation of markets is core to this app and the current modal is barely a placeholder.  This modal should implement the following data collection and flow:
* prompt for text/query with hints and guidance for well-formedness 
* market fee and explanation of what that is
* setting initial liquidity
* number of outcomes with types (true/false, arbitrary labels, decimal/integer range, etc.)

This modal should be a gem of the application and can even be multi-paged.  It also can be slightly more heavy and rich because it doesn't suffer from any on-boarding syndrome.  

Authors are motivated.  Let's help them and make the experience fun and exiting!

**Comment by niran** [comment]
Here's a sketch of what's in my head:

```
Market Question: _________?
Your question should have a yes/no answer.

Decision Date: __/__/__ (date picker)
Your question should be easy for anyone to answer by the date you choose. It's fine to add an extra month or two to be safe.

Your Liquidity Deposit: _____ ether (combobox w/ suggested values)

Trading Fee: _____ ether/trade (combobox w/ suggested values)
Traders are willing to pay higher fees for higher liquidity, but higher fees leave room for other market creators to compete with lower costs.
```

Two rows with two inputs each, with the last help text flowing under the whole second row to illustrate their conceptual connection. We could add a row in the future for selecting the market type and answer categories/ranges.
